services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    # 移除用户映射，使用root用户运行容器
    # user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DATABASE_PATH=/app/data/barcode_scanner.db
    volumes:
      # 将宿主机的 ./backend/data 目录挂载到容器的 /app/data
      # 这样 SQLite 数据库文件就能持久化保存
      - ./backend/data:/app/data
      # 挂载日志目录
      - ./backend/logs:/app/logs
    # 确保容器在重启时也能正确运行
    restart: unless-stopped
    # 直接使用command设置权限并启动应用，不依赖entrypoint.sh
    command: >
      sh -c "
        echo 'Setting up environment...' &&
        mkdir -p /app/data /app/logs &&
        chmod -R 777 /app/data &&
        chmod -R 777 /app/logs &&
        # 初始化数据库文件（如果不存在）
        touch /app/data/barcode_scanner.db &&
        chmod 777 /app/data/barcode_scanner.db &&
        echo 'Starting application...' &&
        gunicorn -c gunicorn_conf.py app.main:app
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend